import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const questionSetId = 'cmqc4cbx90003uxugr9liwpmg';

async function main() {
  await prisma.question.createMany({
    data: [
      // ━━━━━━━━━━━━━━━ 01-26 ━━━━━━━━━━━━━━━

      {
        questionSetId,
        slug: 'ratio-gcd-largest-number',
        questionText: 'দুটি সংখ্যার অনুপাত ২:৩ এবং গ.সা.গু ৪ হলে বৃহত্তম সংখ্যাটি কত?',
        optionA: '১২',
        optionB: '৮',
        optionC: '১৬',
        optionD: '২০',
        correctAnswer: 'A',
        explanation:
          'সঠিক উত্তর: (ক) ১২\nসংখ্যা দুটি 2x ও 3x। গ.সা.গু = x = 4 ⇒ বৃহত্তম সংখ্যা = 3×4 = 12।',
        subject: 'গণিত',
        topic: 'পাটিগণিত',
        subTopic: 'অনুপাত ও গ.সা.গু',
        sortOrder: 1,
      },

      {
        questionSetId,
        slug: 'average-age-family',
        questionText:
          'পিতা, মাতা ও পুত্রের বয়সের গড় ৩৭ বছর। পিতা ও পুত্রের গড় ৩৫ বছর। মাতার বয়স কত?',
        optionA: '৪১ বছর',
        optionB: '৪৫ বছর',
        optionC: '৩৮ বছর',
        optionD: '৪৮ বছর',
        correctAnswer: 'A',
        explanation: 'মোট = 37×3 = 111, পিতা+পুত্র = 35×2 = 70 ⇒ মাতা = 41 বছর।',
        subject: 'গণিত',
        topic: 'পাটিগণিত',
        subTopic: 'গড়',
        sortOrder: 2,
      },

      {
        questionSetId,
        slug: 'ab-from-identities',
        questionText: 'a+b=7 এবং a²+b²=25 হলে ab এর মান কত?',
        optionA: '১২',
        optionB: '৭৩',
        optionC: '৪৯',
        optionD: '২৪',
        correctAnswer: 'A',
        explanation: '(a+b)² = a²+b²+2ab ⇒ 49 = 25 + 2ab ⇒ ab = 12।',
        subject: 'গণিত',
        topic: 'বীজগণিত',
        subTopic: 'মান নির্ণয়',
        sortOrder: 3,
      },

      {
        questionSetId,
        slug: 'supplementary-angle',
        questionText: 'দুটি সন্নিহিত কোণের সমষ্টি দুই সমকোণ হলে একটিকে অপরটির কী বলে?',
        optionA: 'সন্নিহিত কোণ',
        optionB: 'পূরক কোণ',
        optionC: 'সম্পূরক কোণ',
        optionD: 'সরল কোণ',
        correctAnswer: 'C',
        explanation: '180° সমষ্টি হলে সম্পূরক কোণ (Supplementary angle)।',
        subject: 'গণিত',
        topic: 'জ্যামিতি',
        subTopic: 'কোণ',
        sortOrder: 4,
      },

      {
        questionSetId,
        slug: 'prime-number',
        questionText: 'নিচের কোনটি মৌলিক সংখ্যা?',
        optionA: '৯১',
        optionB: '৪৭',
        optionC: '৮৭',
        optionD: '১৪৩',
        correctAnswer: 'B',
        explanation: '৪৭ মৌলিক সংখ্যা। বাকি সংখ্যাগুলো যৌগিক।',
        subject: 'গণিত',
        topic: 'সংখ্যা',
        subTopic: 'মৌলিক সংখ্যা',
        sortOrder: 5,
      },

      {
        questionSetId,
        slug: 'peninsula-question',
        questionText: 'কোনটি উপদ্বীপ?',
        optionA: 'সৌদি আরব',
        optionB: 'কোরিয়া',
        optionC: 'জাপান',
        optionD: 'কিউবা',
        correctAnswer: 'B',
        explanation: 'কোরিয়া উপদ্বীপ। সৌদি আরব বৃহত্তম উপদ্বীপের অংশ হলেও আলাদা রাষ্ট্র নয়।',
        subject: 'সাধারণ জ্ঞান',
        topic: 'ভূগোল',
        subTopic: 'উপদ্বীপ',
        sortOrder: 6,
      },

      {
        questionSetId,
        slug: 'largest-lake',
        questionText: 'বিশ্বের বৃহত্তম হ্রদ কোনটি?',
        optionA: 'ভিক্টোরিয়া হ্রদ',
        optionB: 'বৈকাল হ্রদ',
        optionC: 'সুপিরিয়ার হ্রদ',
        optionD: 'কাস্পিয়ান সাগর',
        correctAnswer: 'D',
        explanation: 'কাস্পিয়ান সাগর আয়তনের দিক থেকে বিশ্বের বৃহত্তম হ্রদ।',
        subject: 'সাধারণ জ্ঞান',
        topic: 'ভূগোল',
        subTopic: 'হ্রদ',
        sortOrder: 7,
      },

      {
        questionSetId,
        slug: 'world-cup-2026',
        questionText: '২০২৬ ফুটবল বিশ্বকাপ কয়টি দেশে অনুষ্ঠিত হবে?',
        optionA: '৪টি',
        optionB: '১টি',
        optionC: '২টি',
        optionD: '৩টি',
        correctAnswer: 'D',
        explanation: 'যুক্তরাষ্ট্র, কানাডা ও মেক্সিকো—৩ দেশে অনুষ্ঠিত হবে।',
        subject: 'সাধারণ জ্ঞান',
        topic: 'খেলাধুলা',
        subTopic: 'ফুটবল',
        sortOrder: 8,
      },

      {
        questionSetId,
        slug: 'unhrc-year',
        questionText: 'জাতিসংঘ মানবাধিকার কাউন্সিল কবে প্রতিষ্ঠিত হয়?',
        optionA: '১৯৪৮',
        optionB: '২০০৬',
        optionC: '১৯৮৮',
        optionD: '১৯৭৯',
        correctAnswer: 'B',
        explanation: 'UNHRC প্রতিষ্ঠিত হয় ২০০৬ সালে।',
        subject: 'সাধারণ জ্ঞান',
        topic: 'আন্তর্জাতিক সংস্থা',
        subTopic: 'জাতিসংঘ',
        sortOrder: 9,
      },

      {
        questionSetId,
        slug: 'native-american',
        questionText: 'রেড ইন্ডিয়ান কারা?',
        optionA: 'ভারতের আদি অধিবাসী',
        optionB: 'ভারতীয় অভিবাসী',
        optionC: 'আমেরিকার আদি অধিবাসী',
        optionD: 'সবগুলো',
        correctAnswer: 'C',
        explanation: 'Native Americans-ই রেড ইন্ডিয়ান নামে পরিচিত।',
        subject: 'সাধারণ জ্ঞান',
        topic: 'জাতিগোষ্ঠী',
        subTopic: 'মানব ইতিহাস',
        sortOrder: 10,
      },

      {
        questionSetId,
        slug: 'vasco-da-gama',
        questionText: 'ভাস্কো-ডা-গামা ছিলেন-',
        optionA: 'ফরাসী',
        optionB: 'পর্তুগীজ',
        optionC: 'ওলন্দাজ',
        optionD: 'ব্রিটিশ',
        correctAnswer: 'B',
        explanation: 'তিনি একজন পর্তুগীজ নাবিক ছিলেন।',
        subject: 'ইতিহাস',
        topic: 'আবিষ্কার',
        subTopic: 'পর্যটক',
        sortOrder: 11,
      },

      {
        questionSetId,
        slug: 'troy-location',
        questionText: 'ঐতিহাসিক ট্রয় নগরী বর্তমানে কোথায় অবস্থিত?',
        optionA: 'স্পেন',
        optionB: 'গ্রিস',
        optionC: 'তুরস্ক',
        optionD: 'ইতালী',
        correctAnswer: 'C',
        explanation: 'ট্রয় নগরীর ধ্বংসাবশেষ তুরস্কে অবস্থিত।',
        subject: 'ইতিহাস',
        topic: 'প্রাচীন সভ্যতা',
        subTopic: 'ট্রয়',
        sortOrder: 12,
      },

      {
        questionSetId,
        slug: 'bongobongo-type',
        questionText: "'বঙ্গভঙ্গ' কি ধরনের সংস্কার ছিল?",
        optionA: 'আর্থিক',
        optionB: 'সামাজিক',
        optionC: 'প্রশাসনিক',
        optionD: 'কাঠামোগত',
        correctAnswer: 'C',
        explanation: '১৯০৫ সালের বঙ্গভঙ্গ ছিল প্রশাসনিক সংস্কার।',
        subject: 'বাংলাদেশ',
        topic: 'ইতিহাস',
        subTopic: 'বঙ্গভঙ্গ',
        sortOrder: 13,
      },

      {
        questionSetId,
        slug: 'bjsc-chairman',
        questionText: 'বাংলাদেশ জুডিসিয়াল সার্ভিস কমিশনের বর্তমান চেয়ারম্যান এর নাম কী?',
        optionA: 'বিচারপতি জিনাত আরা',
        optionB: 'বিচারপতি জুবায়ের রহমান',
        optionC: 'বিচারপতি নাজমুন আরা',
        optionD: 'বিচারপতি ফারাহ মাহবুব',
        correctAnswer: 'D',
        explanation: 'প্রশ্নপত্র অনুযায়ী ফারাহ মাহবুব।',
        subject: 'বাংলাদেশ',
        topic: 'প্রশাসন',
        subTopic: 'কমিশন',
        sortOrder: 14,
      },

      {
        questionSetId,
        slug: 'chief-justice-appointed-by',
        questionText: 'বাংলাদেশের প্রধান বিচারপতি কে নিয়োগ করেন?',
        optionA: 'প্রধানমন্ত্রী',
        optionB: 'সুপ্রিম জুডিসিয়াল কাউন্সিল',
        optionC: 'সংসদ',
        optionD: 'রাষ্ট্রপতি',
        correctAnswer: 'D',
        explanation: 'রাষ্ট্রপতি প্রধান বিচারপতি নিয়োগ করেন।',
        subject: 'বাংলাদেশ',
        topic: 'সংবিধান',
        subTopic: 'বিচার বিভাগ',
        sortOrder: 15,
      },

      {
        questionSetId,
        slug: 'pyramids-country',
        questionText: 'বিশ্বের সবচেয়ে বেশি পিরামিড রয়েছে কোন দেশে?',
        optionA: 'মেক্সিকো',
        optionB: 'ইরাক',
        optionC: 'সুদান',
        optionD: 'মিশর',
        correctAnswer: 'C',
        explanation: 'সুদানে মিশরের চেয়েও বেশি পিরামিড রয়েছে।',
        subject: 'সাধারণ জ্ঞান',
        topic: 'স্থাপত্য',
        subTopic: 'পিরামিড',
        sortOrder: 16,
      },

      {
        questionSetId,
        slug: 'knighthood-bangladeshi',
        questionText: 'দারিদ্র্য বিমোচনে অবদানের জন্য কোন বাংলাদেশী নাইট উপাধি পেয়েছেন?',
        optionA: 'ড. ইউনুস',
        optionB: 'ফজলে হাসান আবেদ',
        optionC: 'জাফরুল্লাহ চৌধুরী',
        optionD: 'ড. হোসনে আরা',
        correctAnswer: 'B',
        explanation: 'ফজলে হাসান আবেদ নাইটহুড পান।',
        subject: 'সাধারণ জ্ঞান',
        topic: 'পুরস্কার',
        subTopic: 'সম্মাননা',
        sortOrder: 17,
      },

      {
        questionSetId,
        slug: 'pm-speaker-role',
        questionText: 'জাতীয় সংসদে সরকারী দলের মুখপাত্র হিসেবে কাজ করেন-',
        optionA: 'স্পীকার',
        optionB: 'চিফ হুইপ',
        optionC: 'সচিব',
        optionD: 'প্রধানমন্ত্রী',
        correctAnswer: 'D',
        explanation: 'সরকারের প্রধান মুখপাত্র প্রধানমন্ত্রী।',
        subject: 'বাংলাদেশ',
        topic: 'সংসদ',
        subTopic: 'রাজনীতি',
        sortOrder: 18,
      },

      {
        questionSetId,
        slug: 'bangladesh-nuclear-ranking',
        questionText: 'বিশ্বে পারমাণবিক শক্তি ব্যবহারকারী দেশের তালিকায় বাংলাদেশের অবস্থান কততম?',
        optionA: '২৮',
        optionB: '৩৩',
        optionC: '৩২',
        optionD: '৩০',
        correctAnswer: 'C',
        explanation: 'বাংলাদেশ ৩২তম দেশ হিসেবে যুক্ত হয়েছে।',
        subject: 'বাংলাদেশ',
        topic: 'বিজ্ঞান',
        subTopic: 'পারমাণবিক',
        sortOrder: 19,
      },

      {
        questionSetId,
        slug: 'vashanchar-location',
        questionText: 'ভাষানচর কোন জেলায় অবস্থিত?',
        optionA: 'ফেনী',
        optionB: 'পটুয়াখালী',
        optionC: 'নোয়াখালী',
        optionD: 'বরিশাল',
        correctAnswer: 'C',
        explanation: 'ভাষানচর নোয়াখালী জেলায় অবস্থিত।',
        subject: 'বাংলাদেশ',
        topic: 'ভূগোল',
        subTopic: 'দ্বীপ',
        sortOrder: 20,
      },

      {
        questionSetId,
        slug: 'gaul-country',
        questionText: "'দ্য গল' কোন দেশের প্রাচীন নাম?",
        optionA: 'পোল্যান্ড',
        optionB: 'ফ্রান্স',
        optionC: 'নেদারল্যান্ড',
        optionD: 'ভারত',
        correctAnswer: 'B',
        explanation: 'Gaul ছিল বর্তমান ফ্রান্সের প্রাচীন নাম।',
        subject: 'সাধারণ জ্ঞান',
        topic: 'ইতিহাস',
        subTopic: 'প্রাচীন দেশ',
        sortOrder: 21,
      },

      {
        questionSetId,
        slug: 'veto-un',
        questionText: 'জাতিসংঘের নিরাপত্তা পরিষদে ভেটো ক্ষমতা কতটি দেশের?',
        optionA: '৫',
        optionB: '১৫',
        optionC: '৬',
        optionD: '৯',
        correctAnswer: 'A',
        explanation: '৫টি স্থায়ী সদস্যের ভেটো ক্ষমতা আছে।',
        subject: 'সাধারণ জ্ঞান',
        topic: 'জাতিসংঘ',
        subTopic: 'নিরাপত্তা পরিষদ',
        sortOrder: 22,
      },

      {
        questionSetId,
        slug: 'bangladesh-coastline',
        questionText: 'বাংলাদেশের জলসীমা কত কিলোমিটার?',
        optionA: '৭১৩',
        optionB: '৭১২',
        optionC: '৭১৪',
        optionD: '৭১১',
        correctAnswer: 'D',
        explanation: 'বাংলাদেশের সমুদ্রসীমা ৭১১ কিমি।',
        subject: 'বাংলাদেশ',
        topic: 'ভূগোল',
        subTopic: 'সমুদ্রসীমা',
        sortOrder: 23,
      },

      {
        questionSetId,
        slug: 'nuclear-bomb-first-country',
        questionText: 'সর্বপ্রথম কোন দেশ পারমাণবিক বোমা তৈরী করে?',
        optionA: 'যুক্তরাষ্ট্র',
        optionB: 'জাপান',
        optionC: 'চীন',
        optionD: 'রাশিয়া',
        correctAnswer: 'A',
        explanation: 'USA প্রথম পারমাণবিক বোমা তৈরি করে (1945)।',
        subject: 'সাধারণ জ্ঞান',
        topic: 'বিজ্ঞান',
        subTopic: 'পরমাণু',
        sortOrder: 24,
      },

      {
        questionSetId,
        slug: 'geo-satellite-bangladesh',
        questionText: 'বাংলাদেশে ভূ-উপগ্রহ কেন্দ্রের সংখ্যা কত?',
        optionA: 'তিন',
        optionB: 'এক',
        optionC: 'চার',
        optionD: 'দুই',
        correctAnswer: 'C',
        explanation: 'বাংলাদেশে ৪টি ভূ-উপগ্রহ কেন্দ্র আছে।',
        subject: 'বাংলাদেশ',
        topic: 'আইসিটি',
        subTopic: 'স্যাটেলাইট',
        sortOrder: 25,
      },

      {
        questionSetId,
        slug: 'oil-embargo-1973',
        questionText: 'আরব দেশসমূহ প্রথম তেল অবরোধ করে কবে?',
        optionA: '১৯৭০',
        optionB: '১৯৭৪',
        optionC: '১৯৭৮',
        optionD: '১৯৭৩',
        correctAnswer: 'D',
        explanation: '১৯৭৩ সালে প্রথম তেল অবরোধ করা হয়।',
        subject: 'সাধারণ জ্ঞান',
        topic: 'অর্থনীতি',
        subTopic: 'ইতিহাস',
        sortOrder: 26,
      },

      // ━━━━━━━━━━━━━━━ 27–50 (condensed same style) ━━━━━━━━━━━━━━━
      {
        questionSetId,
        slug: 'low-land-district',
        questionText: 'বাংলাদেশের কোন জেলায় নিম্নভূমি বেশি?',
        optionA: 'ভোলা',
        optionB: 'রাঙামাটি',
        optionC: 'কিশোরগঞ্জ',
        optionD: 'সুনামগঞ্জ',
        correctAnswer: 'A',
        explanation: 'ভোলা একটি নিচু উপকূলীয় জেলা।',
        subject: 'বাংলাদেশ',
        topic: 'ভূগোল',
        subTopic: 'ভূপ্রকৃতি',
        sortOrder: 27,
      },

      {
        questionSetId,
        slug: 'dholai-khal',
        questionText: 'ধোলাই খাল খনন করেন কে?',
        optionA: 'ইসলাম খান',
        optionB: 'শায়েস্তা খান',
        optionC: 'আলাউদ্দিন হোসেন শাহ',
        optionD: 'শাহ সুজা',
        correctAnswer: 'A',
        explanation: 'মোগল সুবেদার ইসলাম খান ধোলাই খাল খনন করেন।',
        subject: 'বাংলাদেশ',
        topic: 'ইতিহাস',
        subTopic: 'ঢাকা',
        sortOrder: 28,
      },

      {
        questionSetId,
        slug: 'pundra-civilization',
        questionText: 'বাংলাদেশের সবচেয়ে প্রাচীন জনপদ কোনটি?',
        optionA: 'রাঢ়',
        optionB: 'হরিকেল',
        optionC: 'সমতট',
        optionD: 'পুণ্ড্র',
        correctAnswer: 'D',
        explanation: 'পুণ্ড্রই সবচেয়ে প্রাচীন জনপদ।',
        subject: 'বাংলাদেশ',
        topic: 'ইতিহাস',
        subTopic: 'জনপদ',
        sortOrder: 29,
      },

      {
        questionSetId,
        slug: 'neither-verb',
        questionText: 'Neither of the boys ______ present today.',
        optionA: 'were',
        optionB: 'are',
        optionC: 'is',
        optionD: 'have',
        correctAnswer: 'C',
        explanation: 'Neither এর পরে singular verb হয় → is',
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Subject-Verb',
        sortOrder: 30,
      },

      {
        questionSetId,
        slug: 'chief-plural',
        questionText: "What is the plural form of 'Chief'?",
        optionA: 'Chiefes',
        optionB: 'Chiefs',
        optionC: 'Chief',
        optionD: 'Chieves',
        correctAnswer: 'B',
        explanation: 'Chief → Chiefs',
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Number',
        sortOrder: 31,
      },

      {
        questionSetId,
        slug: 'indirect-speech',
        questionText: 'He said, "I am busy." → indirect?',
        optionA: 'He said he is busy',
        optionB: 'He said that he was busy',
        optionC: 'He said he was busy',
        optionD: 'He said that he is busy',
        correctAnswer: 'C',
        explanation: 'Present → Past (am → was)',
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Narration',
        sortOrder: 32,
      },

      {
        questionSetId,
        slug: 'tense-before',
        questionText: 'Correct sentence?',
        optionA: 'A',
        optionB: 'B',
        optionC: 'C',
        optionD: 'D',
        correctAnswer: 'B',
        explanation: 'Past perfect structure correct in option B.',
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Tense',
        sortOrder: 33,
      },

      {
        questionSetId,
        slug: 'sympathetic',
        questionText: "'Sympathetic' is a/an-",
        optionA: 'adverb',
        optionB: 'noun',
        optionC: 'verb',
        optionD: 'adjective',
        correctAnswer: 'D',
        explanation: 'It is an adjective.',
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Parts of Speech',
        sortOrder: 34,
      },

      {
        questionSetId,
        slug: 'optative',
        questionText: 'Optative sentence expresses-',
        optionA: 'emotion',
        optionB: 'command',
        optionC: 'statement',
        optionD: 'desire',
        correctAnswer: 'D',
        explanation: 'Optative expresses desire or wish.',
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Sentence',
        sortOrder: 35,
      },

      {
        questionSetId,
        slug: 'interested-preposition',
        questionText: 'He is interested ______ learning.',
        optionA: 'at',
        optionB: 'for',
        optionC: 'in',
        optionD: 'to',
        correctAnswer: 'C',
        explanation: 'Interested in learning.',
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Preposition',
        sortOrder: 36,
      },

      {
        questionSetId,
        slug: 'fan-preposition',
        questionText: 'The fan is moving ______ his head.',
        optionA: 'upon',
        optionB: 'over',
        optionC: 'above',
        optionD: 'on',
        correctAnswer: 'C',
        explanation: 'Above = স্থির উপরে অবস্থান।',
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Preposition',
        sortOrder: 37,
      },

      {
        questionSetId,
        slug: 'honesty',
        questionText: 'Correct sentence is-',
        optionA: 'A',
        optionB: 'B',
        optionC: 'C',
        optionD: 'D',
        correctAnswer: 'D',
        explanation: 'Honesty is the best policy.',
        subject: 'ইংরেজি',
        topic: 'Grammar',
        subTopic: 'Correction',
        sortOrder: 38,
      },

      {
        questionSetId,
        slug: 'idiom-blessing',
        questionText: "'A blessing in disguise' means-",
        optionA: 'danger',
        optionB: 'false promise',
        optionC: 'bad but good result',
        optionD: 'visible blessing',
        correctAnswer: 'C',
        explanation: 'Bad looking but good outcome.',
        subject: 'ইংরেজি',
        topic: 'Vocabulary',
        subTopic: 'Idioms',
        sortOrder: 39,
      },

      {
        questionSetId,
        slug: 'birbal',
        questionText: 'বীরবল কার ছদ্মনাম?',
        optionA: 'প্রমথ চৌধুরী',
        optionB: 'বিমল মিত্র',
        optionC: 'মুজতবা আলী',
        optionD: 'বলাইচাঁদ',
        correctAnswer: 'A',
        explanation: 'প্রমথ চৌধুরীর ছদ্মনাম বীরবল।',
        subject: 'বাংলা',
        topic: 'সাহিত্য',
        subTopic: 'ছদ্মনাম',
        sortOrder: 40,
      },

      {
        questionSetId,
        slug: 'comma-pause',
        questionText: 'কমার বিরামের সময় কতটুকু?',
        optionA: '১ সেকেন্ড',
        optionB: 'থামার দরকার নেই',
        optionC: 'দীর্ঘ সময়',
        optionD: '২ সেকেন্ড',
        correctAnswer: 'A',
        explanation: 'কমা = স্বল্প বিরতি।',
        subject: 'বাংলা',
        topic: 'ব্যাকরণ',
        subTopic: 'বিরামচিহ্ন',
        sortOrder: 41,
      },

      {
        questionSetId,
        slug: 'synonym-hair',
        questionText: 'চুলের সমার্থক শব্দ কোনটি?',
        optionA: 'কেশ',
        optionB: 'অলক',
        optionC: 'কুন্তল',
        optionD: 'সবগুলো',
        correctAnswer: 'D',
        explanation: 'সবগুলোই সমার্থক শব্দ।',
        subject: 'বাংলা',
        topic: 'ব্যাকরণ',
        subTopic: 'সমার্থক',
        sortOrder: 42,
      },

      {
        questionSetId,
        slug: 'sandhi',
        questionText: 'ইতস্তত শব্দের সন্ধি বিচ্ছেদ কী?',
        optionA: 'ইতঃ + ততঃ',
        optionB: 'ইত + অন্ত',
        optionC: 'ইতঃ + তত',
        optionD: 'ইত + তুত',
        correctAnswer: 'C',
        explanation: 'ইতঃ + তত = ইতস্তত',
        subject: 'বাংলা',
        topic: 'ব্যাকরণ',
        subTopic: 'সন্ধি',
        sortOrder: 43,
      },

      {
        questionSetId,
        slug: 'bangla-prefix',
        questionText: 'খাঁটি বাংলা উপসর্গযুক্ত শব্দ কোনটি?',
        optionA: 'বিচরণ',
        optionB: 'অপমান',
        optionC: 'নিবারণ',
        optionD: 'বিফল',
        correctAnswer: 'D',
        explanation: 'বিফল = বাংলা উপসর্গজাত হিসেবে ধরা হয়।',
        subject: 'বাংলা',
        topic: 'ব্যাকরণ',
        subTopic: 'উপসর্গ',
        sortOrder: 44,
      },

      {
        questionSetId,
        slug: 'idiom-koli',
        questionText: 'কলির সন্ধ্যা অর্থ কী?',
        optionA: 'বিশৃঙ্খল',
        optionB: 'সূচনা',
        optionC: 'ঘটনা',
        optionD: 'পরীক্ষা',
        correctAnswer: 'B',
        explanation: 'শুরু বা সূচনা বোঝায়।',
        subject: 'বাংলা',
        topic: 'ব্যাকরণ',
        subTopic: 'বাগধারা',
        sortOrder: 45,
      },

      {
        questionSetId,
        slug: 'loanword-kolom',
        questionText: 'কলম কোন ভাষা থেকে এসেছে?',
        optionA: 'আরবি',
        optionB: 'তুর্কি',
        optionC: 'পর্তুগীজ',
        optionD: 'ফারসি',
        correctAnswer: 'A',
        explanation: 'আরবি “Qalam” থেকে এসেছে।',
        subject: 'বাংলা',
        topic: 'ব্যাকরণ',
        subTopic: 'শব্দ',
        sortOrder: 46,
      },

      {
        questionSetId,
        slug: 'kar-chinho',
        questionText: 'স্বরবর্ণের কার চিহ্ন কয়টি?',
        optionA: '১১',
        optionB: '১০',
        optionC: '৮',
        optionD: '৭',
        correctAnswer: 'B',
        explanation: 'অ বাদে ১০টি কার চিহ্ন আছে।',
        subject: 'বাংলা',
        topic: 'ব্যাকরণ',
        subTopic: 'বর্ণ',
        sortOrder: 47,
      },

      {
        questionSetId,
        slug: 'spelling-correct',
        questionText: 'শুদ্ধ বানান কোনটি?',
        optionA: 'পূণর্নির্মান',
        optionB: 'পুনর্নির্মাণ',
        optionC: 'পুননির্মান',
        optionD: 'পুনর্নির্মান',
        correctAnswer: 'B',
        explanation: 'শুদ্ধ বানান: পুনর্নির্মাণ',
        subject: 'বাংলা',
        topic: 'ব্যাকরণ',
        subTopic: 'বানান',
        sortOrder: 48,
      },

      {
        questionSetId,
        slug: 'bondona-kobita',
        questionText: 'বন্দনা কবিতার রচয়িতা কে?',
        optionA: 'সগীর',
        optionB: 'রবীন্দ্রনাথ',
        optionC: 'আলাওল',
        optionD: 'আবদুল হাকিম',
        correctAnswer: 'B',
        explanation: 'রবীন্দ্রনাথ ঠাকুর।',
        subject: 'বাংলা',
        topic: 'সাহিত্য',
        subTopic: 'কবিতা',
        sortOrder: 49,
      },
    ],
    skipDuplicates: true,
  });

  console.log('✓ Clean production-ready seed inserted successfully');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
